"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.bapaSitaramRequestData = exports.ecoStarRequestData = exports.anjaliRequestData = exports.maitriRequestData = void 0;
const config_1 = require("../config");
const maitriRequestData = (page) => {
    return {
        method: 'POST',
        apiURL: config_1.MAITRI_API_URL,
        token: config_1.MAITRI_AUTH_TOKEN,
        data: {
            Code: 0,
            FromCarat: 0,
            ToCarat: 50,
            FromRatio: 0,
            ToRatio: 1000,
            FromLength: 0,
            ToLength: 1000,
            FromWidth: 0,
            ToWidth: 1000,
            FromDepth: 0,
            ToDepth: 1000,
            FromDepthPercent: 0,
            ToDepthPercent: 100,
            FromTablePercent: 0,
            ToTablePercent: 100,
            IsForPortal: false,
            PortalId: 0,
            Rejected: 0,
            NoBGM: 0,
            HeartsAndArrows: 0,
            EyeClean: 0,
            ListPackets: [],
            ListLabIds: [],
            ListShapeIds: [],
            ListTypeIds: [],
            ListColorIds: [],
            ListClarityIds: [],
            ListCutIds: [],
            ListPolishIds: [],
            ListSymmIds: [],
            ListFluoIds: [],
            ListFancyColorIntensityIds: [],
            ListFancyColorOverToneIds: [],
            ListFancyColorIds: [],
            ListBranchIds: [],
            ListUsers: [],
            ListDepartmentIds: [],
            ListStockStatuses: [],
            ListSharedUserIds: [],
            ListWorkerIds: [],
            ListIncludePartyIds: [],
            ListExcludePartyIds: [],
            ListLab: [
                {
                    Code: 111,
                    Value: 'IGI',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 164,
                    Value: 'GIA',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 110,
                    Value: 'GCAL',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 168,
                    Value: 'None',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
            ],
            ListShape: [
                {
                    Code: 36,
                    Value: 'Round',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 9,
                    Value: 'Cushion',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 53,
                    Value: 'Heart',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 28,
                    Value: 'Princess',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 51,
                    Value: 'Emerald',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 24,
                    Value: 'Pear',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 50,
                    Value: 'Marquise',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 66,
                    Value: 'Oval',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 155,
                    Value: 'Asscher',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 35,
                    Value: 'Radiant',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 29,
                    Value: 'Square Radiant',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 309,
                    Value: 'Baguette',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
            ],
            ListNonShape: [],
            ListColor: [
                {
                    Code: 49,
                    Value: 'D',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 70,
                    Value: 'E',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 14,
                    Value: 'F',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 31,
                    Value: 'G',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 2,
                    Value: 'H',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 40,
                    Value: 'I',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 69,
                    Value: 'J',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 22,
                    Value: 'K',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 5,
                    Value: 'L',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 48,
                    Value: 'M',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
            ],
            ListClarity: [
                {
                    Code: 4,
                    Value: 'FL',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 162,
                    Value: 'IF',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 131,
                    Value: 'VVS1',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 45,
                    Value: 'VVS2',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 47,
                    Value: 'VS1',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 58,
                    Value: 'VS2',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 32,
                    Value: 'SI1',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 16,
                    Value: 'SI2',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 46,
                    Value: 'SI3',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 41,
                    Value: 'I1',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 20,
                    Value: 'I2',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 7,
                    Value: 'I3',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
            ],
            ListCut: [
                {
                    Code: 26,
                    FullVal: 'Ideal',
                    Value: 'ID',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 19,
                    FullVal: 'Excellent',
                    Value: 'EX',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 63,
                    FullVal: 'Very good',
                    Value: 'VG',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 157,
                    FullVal: 'Good',
                    Value: 'GD',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 195,
                    FullVal: 'None',
                    Value: '-',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
            ],
            ListPolish: [
                {
                    Code: 23,
                    FullVal: 'Excellent',
                    Value: 'EX',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 43,
                    FullVal: 'Very good',
                    Value: 'VG',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 52,
                    FullVal: 'Good',
                    Value: 'GD',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
            ],
            ListSymm: [
                {
                    Code: 42,
                    FullVal: 'Excellent',
                    Value: 'EX',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 12,
                    FullVal: 'Very good',
                    Value: 'VG',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 158,
                    FullVal: 'Good',
                    Value: 'GD',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
            ],
            ListFluo: [
                {
                    Code: 30,
                    Value: 'None',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 60,
                    Value: 'Faint',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 159,
                    Value: 'Medium',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 160,
                    Value: 'Strong',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 161,
                    Value: 'Very Strong',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
            ],
            ListType: [
                {
                    Code: 311,
                    Value: 'HPHT',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 312,
                    Value: 'CVD',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
            ],
            ListFancyColorIntensity: [
                {
                    Code: 123,
                    Value: 'Fancy',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 124,
                    Value: 'Fancy Dark',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 125,
                    Value: 'Fancy Deep',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 126,
                    Value: 'Fancy Intense',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 127,
                    Value: 'Fancy Light',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 128,
                    Value: 'Fancy Vivid',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 129,
                    Value: 'Light',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 130,
                    Value: 'Very Light',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 170,
                    Value: 'Faint',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
            ],
            ListFancyColorOverTone: [
                {
                    Code: 105,
                    Value: 'Blackish',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 106,
                    Value: 'Brownish',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 107,
                    Value: 'Brownish-Orangy',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 108,
                    Value: 'Orangy',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 109,
                    Value: 'Pinkish',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 175,
                    Value: 'Greenish',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 189,
                    Value: 'Bluish',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 193,
                    Value: 'Yellowish',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 255,
                    Value: 'Greyish-Greenish',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 256,
                    Value: 'Greyish',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
            ],
            ListFancyColor: [
                {
                    Code: 115,
                    Value: 'Black',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 116,
                    Value: 'Blue',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 117,
                    Value: 'Brown',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 118,
                    Value: 'Grey',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 119,
                    Value: 'Orange',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 120,
                    Value: 'Pink',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 121,
                    Value: 'Pink-Brown',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 254,
                    Value: 'Purple',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 187,
                    Value: 'Blue-Green',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 190,
                    Value: 'Green',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 192,
                    Value: 'Yellow-Green',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 257,
                    Value: 'Gray-Green',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
            ],
            ListBranch: [
                {
                    Code: 7,
                    Value: 'New York',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 17,
                    Value: 'Chicago',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
            ],
            ListStockStatus: [
                {
                    Code: 1,
                    Value: 'OnMemo',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 2,
                    Value: 'InStock',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
                {
                    Code: 3,
                    Value: 'OnHold',
                    IsSelected: false,
                    IsShape: false,
                    IsRadioButton: false,
                },
            ],
            PageNo: String(page),
            PageLimit: config_1.UPLOAD_DIAMOND_LIMIT || '100',
            SortColumn: 'Status',
            SortOrder: 'asc',
            FromPrice: 0,
            ToPrice: 0,
        },
    };
};
exports.maitriRequestData = maitriRequestData;
const anjaliRequestData = () => {
    return {
        method: 'POST',
        apiURL: config_1.ANJALI_SOURCE_API_URL,
        token: config_1.ANJALI_SOURCE_AUTH_TOKEN,
    };
};
exports.anjaliRequestData = anjaliRequestData;
const ecoStarRequestData = () => {
    return {
        method: 'GET',
        apiURL: config_1.ECOSTAR_SOURCE_API_URL,
        params: [
            {
                key: 'token',
                value: config_1.ECOSTAR_SOURCE_AUTH_TOKEN,
            },
            {
                key: 'userid',
                value: 'MOTIBAGEMS',
            },
        ],
    };
};
exports.ecoStarRequestData = ecoStarRequestData;
const bapaSitaramRequestData = () => {
    return {
        method: 'GET',
        apiURL: config_1.BAPA_SITARAM_SOURCE_API_URL,
        params: [
            {
                key: 'APIKEY',
                value: config_1.BAPA_SITARAM_API_KEY,
            },
        ],
    };
};
exports.bapaSitaramRequestData = bapaSitaramRequestData;
//# sourceMappingURL=diamondSources.js.map