"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.excelExtensions = exports.uploadViaFileValues = exports.keyToSymbolValues = exports.fancyOvertoneValues = exports.fancyIntensityValues = exports.fancyColorValues = exports.naturalCuletSizeValues = exports.labGrownCuletSizeValues = exports.eyeCleanRange = exports.lusterValues = exports.symmetryValues = exports.polishValues = exports.cutValues = exports.clarityValues = exports.colorValues = exports.shapeValues = exports.naturalLabValues = exports.labGrownLabValues = exports.statusValues = exports.heartsAndArrowsValues = exports.noBGMValues = exports.inscriptionValues = exports.labGrownTypeValues = exports.diamondTypeValues = exports.uploadDiamondsFileHeader = void 0;
exports.uploadDiamondsFileHeader = {
    stoneNo: 'Stone No',
    lab: 'Lab',
    shape: 'Shape',
    carat: 'Carat',
    color: 'Color',
    clarity: 'Clarity',
    cut: 'Cut',
    polish: 'Polish',
    symmetry: 'Symmetry',
    diamondType: 'Diamond Type',
    type: 'Sub Type',
    shade: 'Shade',
    rap: 'Rap $',
    pricePerCarat: 'Price/Carat $',
    discount: 'Discount %',
    price: 'Price $',
    inscription: 'Inscription',
    noBGM: 'No BGM',
    country: 'Country',
    city: 'City',
    luster: 'Luster',
    milky: 'Milky',
    eyeClean: 'Eye Clean %',
    measurement: 'Measurement',
    width: 'Width',
    height: 'Height',
    florescence: 'Florescence',
    inclusion: 'Inclusion',
    extraFacet: 'Extra Facet',
    internalGraining: 'Internal Graining',
    surfaceGraining: 'Surface Graining',
    heartsAndArrows: 'Hearts And Arrows',
    culetSize: 'Culet Size',
    fancyColor: 'Fancy Color',
    fancyIntensity: 'Fancy Intensity',
    fancyOvertone: 'Fancy Overtone',
    length: 'Length',
    depthPercentage: 'Depth %',
    tablePercentage: 'Table %',
    crownAngle: 'Crown Angle',
    crownHeight: 'Crown Height',
    pavilionAngle: 'Pavilion Angle',
    pavilionHeight: 'Pavilion Height',
    starLength: 'Star Length',
    lowerHalves: 'Lower Halves',
    girdleType: 'Girdle Type',
    girdlePercentage: 'Girdle %',
    girdleCondition: 'Girdle Condition',
    ratio: 'Ratio',
    videoLink: 'Video Link',
    imageLink: 'Image Link',
    certificateLink: 'Certificate Link',
    keyToSymbol: 'Key To Symbol',
    notes: 'Notes',
    motibaGemsComment: 'Motiba Gems Comment',
    certificateComment: 'Certificate Comment',
    status: 'Status',
};
exports.diamondTypeValues = ['lab grown', 'natural'];
exports.labGrownTypeValues = ['cvd', 'hpht'];
exports.inscriptionValues = ['yes', 'no'];
exports.noBGMValues = ['yes', 'no'];
exports.heartsAndArrowsValues = ['yes', 'no'];
exports.statusValues = ['available', 'sold'];
exports.labGrownLabValues = ['igi', 'gia', 'hrd', 'none'];
exports.naturalLabValues = ['gia', 'igi', 'hrd', 'fm', 'ngtc', 'iidgr', 'none'];
exports.shapeValues = ['round', 'cushion', 'marquise', 'pear', 'princess', 'heart', 'oval', 'emerald', 'radiant', 'square emerald'];
exports.colorValues = ['d', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q-r', 's-t', 'u-v', 'w-x', 'y-z'];
exports.clarityValues = ['fl', 'if', 'vvs1', 'vvs2', 'vs1', 'vs2', 'si1', 'si2', 'si3', 'i1', 'i2', 'i3'];
exports.cutValues = ['id', 'ex', 'vg', 'gd', 'fr'];
exports.polishValues = ['id', 'ex', 'vg', 'gd', 'fr'];
exports.symmetryValues = ['id', 'ex', 'vg', 'gd', 'fr'];
exports.lusterValues = ['id', 'ex', 'vg', 'gd', 'fr'];
exports.eyeCleanRange = { from: 0, to: 100 };
exports.labGrownCuletSizeValues = ['none', 'pointed', 'long'];
exports.naturalCuletSizeValues = ['non', 'vs', 's', 'm', 'l', 'vl'];
exports.fancyColorValues = [
    'fancy light yellow',
    'gray blue',
    'green blue',
    'light grey blue',
    'vivid green blue',
    'yellow',
    'pink',
    'blue',
    'red',
    'green',
    'purple',
    'orange',
    'violet',
    'gray',
    'black',
    'brown',
    'champagne',
    'cognac',
    'chameleon',
    'white',
    'other',
    'brown yellow',
    'orange yellow',
    'green yellow',
    'orangy yellow',
    'brown pink',
    'purple pink',
    'bluish green',
    'yellow green',
    'pink purple',
    'yellow orange',
    'brown orange',
    'yellow grey',
    'yellow brown',
    'pink brown',
    'orange brown',
    'green chameleon',
];
exports.fancyIntensityValues = [
    'faint',
    'very light',
    'light',
    'fancy light',
    'fancy',
    'fancy dark',
    'fancy intense',
    'fancy vivid',
    'fancy deep',
    'fancy natural',
];
exports.fancyOvertoneValues = [
    'brown',
    'gray',
    'pink',
    'yellow',
    'none',
    'yellowish',
    'pinkish',
    'bluish',
    'reddish',
    'greenish',
    'purplish',
    'orangey',
    'grayish',
    'brownish',
    'brown orangey',
    'brownish greenish',
    'brownish yellowish',
    'grayish greenish',
    'grayish yellowish',
];
exports.keyToSymbolValues = [
    'bearding',
    'chip',
    'crystal surface',
    'flux remnant',
    'internal laser drilling',
    'minor details of polish',
    'pinpoint',
    'brown patch of color',
    'cleavage',
    'etch channel',
    'indented natural',
    'knot',
    'natural',
    'reflecting surface graining',
    'bruise',
    'cloud',
    'extra facet',
    'internal graining',
    'laser drill hole',
    'needle',
    'surface graining',
    'cavity',
    'crystal',
    'feather',
    'internal inscription',
    'manufacturing remnant',
    'no inclusion',
    'twining wisp',
];
exports.uploadViaFileValues = [
    ['NOTE: NOT CASE SENSITIVE', ''],
    ['Diamond Types ', exports.diamondTypeValues.join(', ')],
    ['Lab Grown Types ', exports.labGrownTypeValues.join(', ')],
    ['Inscription ', exports.inscriptionValues.join('/')],
    ['No BGM ', exports.noBGMValues.join('/')],
    ['Hearts and Arrows ', exports.heartsAndArrowsValues.join('/')],
    ['Status ', exports.statusValues.join('/')],
    ['Lab [Lab Grown] ', exports.labGrownLabValues.join(', ')],
    ['Lab [Natural] ', exports.naturalLabValues.join(', ')],
    ['Shape ', exports.shapeValues.join(', ')],
    ['Color ', exports.colorValues.join(', ')],
    ['Clarity ', exports.clarityValues.join(', ')],
    ['Cut ', exports.cutValues.join(', ')],
    ['Polish ', exports.polishValues.join(', ')],
    ['Symmetry ', exports.symmetryValues.join(', ')],
    ['Luster ', exports.lusterValues.join(', ')],
    ['Eye Clean ', `${exports.eyeCleanRange.from} - ${exports.eyeCleanRange.to}`],
    ['Culet Size [Lab grown] ', exports.labGrownCuletSizeValues.join(', ')],
    ['Culet Size [Natural] ', exports.naturalCuletSizeValues.join(', ')],
    ['Fancy Color ', exports.fancyColorValues.join(', ')],
    ['Fancy Intensity ', exports.fancyIntensityValues.join(', ')],
    ['Fancy Overtone ', exports.fancyOvertoneValues.join(', ')],
    ['Key To Symbol ', exports.keyToSymbolValues.join(', ')],
];
exports.excelExtensions = ['xlsx', 'csv', 'xls'];
//# sourceMappingURL=uploadViaFile.js.map