export declare const uploadDiamondsFileHeader: {
    stoneNo: string;
    lab: string;
    shape: string;
    carat: string;
    color: string;
    clarity: string;
    cut: string;
    polish: string;
    symmetry: string;
    diamondType: string;
    type: string;
    shade: string;
    rap: string;
    pricePerCarat: string;
    discount: string;
    price: string;
    inscription: string;
    noBGM: string;
    country: string;
    city: string;
    luster: string;
    milky: string;
    eyeClean: string;
    measurement: string;
    width: string;
    height: string;
    florescence: string;
    inclusion: string;
    extraFacet: string;
    internalGraining: string;
    surfaceGraining: string;
    heartsAndArrows: string;
    culetSize: string;
    fancyColor: string;
    fancyIntensity: string;
    fancyOvertone: string;
    length: string;
    depthPercentage: string;
    tablePercentage: string;
    crownAngle: string;
    crownHeight: string;
    pavilionAngle: string;
    pavilionHeight: string;
    starLength: string;
    lowerHalves: string;
    girdleType: string;
    girdlePercentage: string;
    girdleCondition: string;
    ratio: string;
    videoLink: string;
    imageLink: string;
    certificateLink: string;
    keyToSymbol: string;
    notes: string;
    motibaGemsComment: string;
    certificateComment: string;
    status: string;
};
export declare const diamondTypeValues: string[];
export declare const labGrownTypeValues: string[];
export declare const inscriptionValues: string[];
export declare const noBGMValues: string[];
export declare const heartsAndArrowsValues: string[];
export declare const statusValues: string[];
export declare const labGrownLabValues: string[];
export declare const naturalLabValues: string[];
export declare const shapeValues: string[];
export declare const colorValues: string[];
export declare const clarityValues: string[];
export declare const cutValues: string[];
export declare const polishValues: string[];
export declare const symmetryValues: string[];
export declare const lusterValues: string[];
export declare const eyeCleanRange: {
    from: number;
    to: number;
};
export declare const labGrownCuletSizeValues: string[];
export declare const naturalCuletSizeValues: string[];
export declare const fancyColorValues: string[];
export declare const fancyIntensityValues: string[];
export declare const fancyOvertoneValues: string[];
export declare const keyToSymbolValues: string[];
export declare const uploadViaFileValues: string[][];
export declare const excelExtensions: string[];
