"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.profitHeader = exports.purchaseHeader = exports.orderHeader = exports.diamondHeader = void 0;
const config_1 = require("../config");
const export_interface_1 = require("../interfaces/export.interface");
const helpers_1 = require("./helpers");
exports.diamondHeader = [
    { key: 'srNo', header: 'Sr. No' },
    { key: 'stoneId', header: 'Stone ID', getterKey: 'stoneNo' },
    { key: 'videoLink', header: 'Video', getterKey: '_id', formatterType: export_interface_1.EFormatterType.LINK, webURL: `${config_1.APP_URL}/view-video` },
    { key: 'certificateLink', header: 'Certificate', getterKey: '_id', formatterType: export_interface_1.EFormatterType.LINK, webURL: `${config_1.APP_URL}/view-certificate` },
    { key: 'lab', header: 'Lab', getterKey: 'lab', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'type', header: 'Type', getterKey: 'type', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'inscription', header: 'Inscription', getterKey: 'inscription', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'shape', header: 'Shape', getterKey: 'shape', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'carat', header: 'Carat', style: { numFmt: '0.00' }, getterKey: 'caratWeight', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'color', header: 'Color', getterKey: 'color', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'clarity', header: 'Clarity', getterKey: 'clarity', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'cut', header: 'Cut', getterKey: 'cut', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'polish', header: 'Polish', getterKey: 'polish', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'symmetry', header: 'Symmetry', getterKey: 'symmetry', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'fluorescence', header: 'Fluorescence', getterKey: 'fluorescence', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'rap', header: 'Rap $', style: { numFmt: '0.00' }, getterKey: 'rap', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'discount', header: 'Discount %', style: { numFmt: '0.0000' }, getterKey: 'ourDiscount', formatterType: export_interface_1.EFormatterType.DIGIT },
    {
        key: 'pricePerCarat',
        header: 'Price $ / Carat',
        style: { numFmt: '_($* 0.00_);' },
        getterKey: 'pricePerCarat',
        formatterType: export_interface_1.EFormatterType.DIGIT,
    },
    { key: 'amount', header: 'Total Amount $', style: { numFmt: '_($* 0.00_);' }, getterKey: 'ourPrice', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'location', header: 'Location', getterKey: ['city', 'country'], formatterType: export_interface_1.EFormatterType.FIRST_LETTER_UPPERCASE },
    { key: 'measurement', header: 'Measurement', getterKey: 'measurement' },
    { key: 'depthPercentage', header: 'Depth %', style: { numFmt: '0.00' }, getterKey: 'depthPercentage', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'tablePercentage', header: 'Table %', style: { numFmt: '0.00' }, getterKey: 'tablePercentage', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'heartsAndArrows', header: 'Hearts and Arrows', getterKey: 'heartsAndArrows', formatterType: export_interface_1.EFormatterType.YES_NO },
    { key: 'inclusion', header: 'Inclusion', getterKey: 'inclusion', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'shade', header: 'Shade', getterKey: 'shade', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'milky', header: 'Milky', getterKey: 'milky' },
    { key: 'luster', header: 'Luster', getterKey: 'luster' },
    { key: 'extraFacet', header: 'Extra Facet', getterKey: 'extraFacet' },
    { key: 'internalGraining', header: 'Internal Graining', getterKey: 'internalGraining' },
    { key: 'surfaceGraining', header: 'Surface Graining', getterKey: 'surfaceGraining' },
    {
        key: 'eyeClean',
        header: 'Eye Clean',
        getterKey: 'eyeClean',
        formatterType: export_interface_1.EFormatterType.CUSTOM_FUNCTION,
        getValue: function (value) {
            return (0, helpers_1.getEyeCleanValue)(value).toUpperCase();
        },
    },
    { key: 'ratio', header: 'Ratio', style: { numFmt: '0.00' }, getterKey: 'ratio', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'length', header: 'Length', style: { numFmt: '0.00' }, getterKey: 'length', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'width', header: 'Width', style: { numFmt: '0.00' }, getterKey: 'width', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'height', header: 'Height', style: { numFmt: '0.00' }, getterKey: 'height', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'crownAngle', header: 'Crown Angle', style: { numFmt: '0.00' }, getterKey: 'crownAngle', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'pavilionAngle', header: 'Pavilion Angle', style: { numFmt: '0.00' }, getterKey: 'pavilionAngle', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'crownHeight', header: 'Crown Height', style: { numFmt: '0.00' }, getterKey: 'crownHeight', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'pavilionHeight', header: 'Pavilion Height', style: { numFmt: '0.00' }, getterKey: 'pavilionHeight', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'starLength', header: 'Star Length', getterKey: 'starLength' },
    { key: 'lowerHalves', header: 'Lower Halves', getterKey: 'lowerHalves' },
    { key: 'girdleCondition', header: 'Girdle Condition', getterKey: 'girdleCondition', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE, isMetadata: true },
    {
        key: 'girdlePercentage',
        header: 'Girdle Percentage',
        style: { numFmt: '0.00' },
        getterKey: 'girdlePercentage',
        formatterType: export_interface_1.EFormatterType.DIGIT,
    },
    { key: 'girdleType', header: 'Girdle Type', getterKey: 'girdleType', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'culet', header: 'Culet', getterKey: 'culetSize', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'status', header: 'Status', getterKey: 'status', formatterType: export_interface_1.EFormatterType.REPLACE_WORD, searchValue: '_', newValue: ' ' },
];
exports.orderHeader = [
    { key: 'srNo', header: 'Sr. No' },
    { key: 'orderID', header: 'Order ID', getterKey: 'orderNumber' },
    { key: 'stoneId', header: 'Stone ID', getterKey: 'stoneNo' },
    { key: 'videoLink', header: 'Video', getterKey: '_id', formatterType: export_interface_1.EFormatterType.LINK, webURL: `${config_1.APP_URL}/view-video` },
    { key: 'certificateLink', header: 'Certificate', getterKey: '_id', formatterType: export_interface_1.EFormatterType.LINK, webURL: `${config_1.APP_URL}/view-certificate` },
    { key: 'lab', header: 'Lab', getterKey: 'lab', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'type', header: 'Type', getterKey: 'type', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'inscription', header: 'Inscription', getterKey: 'inscription', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'shape', header: 'Shape', getterKey: 'shape', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'carat', header: 'Carat', style: { numFmt: '0.00' }, getterKey: 'caratWeight', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'color', header: 'Color', getterKey: 'color', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'clarity', header: 'Clarity', getterKey: 'clarity', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'cut', header: 'Cut', getterKey: 'cut', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'polish', header: 'Polish', getterKey: 'polish', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'symmetry', header: 'Symmetry', getterKey: 'symmetry', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'fluorescence', header: 'Fluorescence', getterKey: 'fluorescence', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'rap', header: 'Rap $', style: { numFmt: '0.00' }, getterKey: 'rap', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'discount', header: 'Discount %', style: { numFmt: '0.0000' }, getterKey: 'ourDiscount', formatterType: export_interface_1.EFormatterType.DIGIT },
    {
        key: 'pricePerCarat',
        header: 'Price $ / Carat',
        style: { numFmt: '_($* 0.00_);' },
        getterKey: 'pricePerCarat',
        formatterType: export_interface_1.EFormatterType.DIGIT,
    },
    { key: 'amount', header: 'Total Amount $', style: { numFmt: '_($* 0.00_);' }, getterKey: 'ourPrice', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'location', header: 'Location', getterKey: ['city', 'country'], formatterType: export_interface_1.EFormatterType.FIRST_LETTER_UPPERCASE },
    { key: 'measurement', header: 'Measurement', getterKey: 'measurement' },
    { key: 'depthPercentage', header: 'Depth %', style: { numFmt: '0.00' }, getterKey: 'depthPercentage', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'tablePercentage', header: 'Table %', style: { numFmt: '0.00' }, getterKey: 'tablePercentage', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'heartsAndArrows', header: 'Hearts and Arrows', getterKey: 'heartsAndArrows', formatterType: export_interface_1.EFormatterType.YES_NO },
    { key: 'inclusion', header: 'Inclusion', getterKey: 'inclusion', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'shade', header: 'Shade', getterKey: 'shade', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'milky', header: 'Milky', getterKey: 'milky' },
    { key: 'luster', header: 'Luster', getterKey: 'luster' },
    { key: 'extraFacet', header: 'Extra Facet', getterKey: 'extraFacet' },
    { key: 'internalGraining', header: 'Internal Graining', getterKey: 'internalGraining' },
    { key: 'surfaceGraining', header: 'Surface Graining', getterKey: 'surfaceGraining' },
    {
        key: 'eyeClean',
        header: 'Eye Clean',
        getterKey: 'eyeClean',
        formatterType: export_interface_1.EFormatterType.CUSTOM_FUNCTION,
        getValue: function (value) {
            return (0, helpers_1.getEyeCleanValue)(value).toUpperCase();
        },
    },
    { key: 'ratio', header: 'Ratio', style: { numFmt: '0.00' }, getterKey: 'ratio', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'length', header: 'Length', style: { numFmt: '0.00' }, getterKey: 'length', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'width', header: 'Width', style: { numFmt: '0.00' }, getterKey: 'width', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'height', header: 'Height', style: { numFmt: '0.00' }, getterKey: 'height', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'crownAngle', header: 'Crown Angle', style: { numFmt: '0.00' }, getterKey: 'crownAngle', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'pavilionAngle', header: 'Pavilion Angle', style: { numFmt: '0.00' }, getterKey: 'pavilionAngle', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'crownHeight', header: 'Crown Height', style: { numFmt: '0.00' }, getterKey: 'crownHeight', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'pavilionHeight', header: 'Pavilion Height', style: { numFmt: '0.00' }, getterKey: 'pavilionHeight', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'starLength', header: 'Star Length', getterKey: 'starLength' },
    { key: 'lowerHalves', header: 'Lower Halves', getterKey: 'lowerHalves' },
    { key: 'girdleCondition', header: 'Girdle Condition', getterKey: 'girdleCondition', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE, isMetadata: true },
    {
        key: 'girdlePercentage',
        header: 'Girdle Percentage',
        style: { numFmt: '0.00' },
        getterKey: 'girdlePercentage',
        formatterType: export_interface_1.EFormatterType.DIGIT,
    },
    { key: 'girdleType', header: 'Girdle Type', getterKey: 'girdleType', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'culet', header: 'Culet', getterKey: 'culetSize', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'status', header: 'Status', getterKey: 'status', formatterType: export_interface_1.EFormatterType.REPLACE_WORD, searchValue: '_', newValue: ' ' },
];
exports.purchaseHeader = [
    { key: 'srNo', header: 'Sr. No' },
    {
        key: 'purchaseDate',
        header: 'Purchase Date',
        getterKey: 'date',
        formatterType: export_interface_1.EFormatterType.CUSTOM_FUNCTION,
        getValue: function (value) {
            return (0, helpers_1.formatDate)(new Date(value));
        },
    },
    { key: 'orderID', header: 'Order ID', getterKey: 'orderNumber' },
    { key: 'stoneId', header: 'Stone ID', getterKey: 'stoneNo' },
    { key: 'videoLink', header: 'Video', getterKey: '_id', formatterType: export_interface_1.EFormatterType.LINK, webURL: `${config_1.APP_URL}/view-video` },
    { key: 'certificateLink', header: 'Certificate', getterKey: '_id', formatterType: export_interface_1.EFormatterType.LINK, webURL: `${config_1.APP_URL}/view-certificate` },
    { key: 'lab', header: 'Lab', getterKey: 'lab', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'type', header: 'Type', getterKey: 'type', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'inscription', header: 'Inscription', getterKey: 'inscription', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'shape', header: 'Shape', getterKey: 'shape', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'carat', header: 'Carat', style: { numFmt: '0.00' }, getterKey: 'caratWeight', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'color', header: 'Color', getterKey: 'color', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'clarity', header: 'Clarity', getterKey: 'clarity', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'cut', header: 'Cut', getterKey: 'cut', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'polish', header: 'Polish', getterKey: 'polish', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'symmetry', header: 'Symmetry', getterKey: 'symmetry', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'fluorescence', header: 'Fluorescence', getterKey: 'fluorescence', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'rap', header: 'Rap $', style: { numFmt: '0.00' }, getterKey: 'finalRap', formatterType: export_interface_1.EFormatterType.DIGIT },
    {
        key: 'discount',
        header: 'Discount %',
        style: { numFmt: '0.0000' },
        getterKey: 'finalDiscount',
        formatterType: export_interface_1.EFormatterType.DIGIT,
    },
    {
        key: 'pricePerCarat',
        header: 'Price $ / Carat',
        style: { numFmt: '_($* 0.00_);' },
        getterKey: 'finalPrice',
        formatterType: export_interface_1.EFormatterType.DIGIT,
    },
    {
        key: 'amount',
        header: 'Total Amount $',
        style: { numFmt: '_($* 0.00_);' },
        getterKey: 'finalTotalPrice',
        formatterType: export_interface_1.EFormatterType.DIGIT,
    },
    { key: 'location', header: 'Location', getterKey: ['city', 'country'], formatterType: export_interface_1.EFormatterType.FIRST_LETTER_UPPERCASE },
    { key: 'measurement', header: 'Measurement', getterKey: 'measurement' },
    { key: 'depthPercentage', header: 'Depth %', style: { numFmt: '0.00' }, getterKey: 'depthPercentage', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'tablePercentage', header: 'Table %', style: { numFmt: '0.00' }, getterKey: 'tablePercentage', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'heartsAndArrows', header: 'Hearts and Arrows', getterKey: 'heartsAndArrows', formatterType: export_interface_1.EFormatterType.YES_NO },
    { key: 'inclusion', header: 'Inclusion', getterKey: 'inclusion', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'shade', header: 'Shade', getterKey: 'shade', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'milky', header: 'Milky', getterKey: 'milky' },
    { key: 'luster', header: 'Luster', getterKey: 'luster' },
    { key: 'extraFacet', header: 'Extra Facet', getterKey: 'extraFacet' },
    { key: 'internalGraining', header: 'Internal Graining', getterKey: 'internalGraining' },
    { key: 'surfaceGraining', header: 'Surface Graining', getterKey: 'surfaceGraining' },
    {
        key: 'eyeClean',
        header: 'Eye Clean',
        getterKey: 'eyeClean',
        formatterType: export_interface_1.EFormatterType.CUSTOM_FUNCTION,
        getValue: function (value) {
            return (0, helpers_1.getEyeCleanValue)(value).toUpperCase();
        },
    },
    { key: 'ratio', header: 'Ratio', style: { numFmt: '0.00' }, getterKey: 'ratio', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'length', header: 'Length', style: { numFmt: '0.00' }, getterKey: 'length', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'width', header: 'Width', style: { numFmt: '0.00' }, getterKey: 'width', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'height', header: 'Height', style: { numFmt: '0.00' }, getterKey: 'height', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'crownAngle', header: 'Crown Angle', style: { numFmt: '0.00' }, getterKey: 'crownAngle', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'pavilionAngle', header: 'Pavilion Angle', style: { numFmt: '0.00' }, getterKey: 'pavilionAngle', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'crownHeight', header: 'Crown Height', style: { numFmt: '0.00' }, getterKey: 'crownHeight', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'pavilionHeight', header: 'Pavilion Height', style: { numFmt: '0.00' }, getterKey: 'pavilionHeight', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'starLength', header: 'Star Length', getterKey: 'starLength' },
    { key: 'lowerHalves', header: 'Lower Halves', getterKey: 'lowerHalves' },
    { key: 'girdleCondition', header: 'Girdle Condition', getterKey: 'girdleCondition', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE, isMetadata: true },
    {
        key: 'girdlePercentage',
        header: 'Girdle Percentage',
        style: { numFmt: '0.00' },
        getterKey: 'girdlePercentage',
        formatterType: export_interface_1.EFormatterType.DIGIT,
    },
    { key: 'girdleType', header: 'Girdle Type', getterKey: 'girdleType', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'culet', header: 'Culet', getterKey: 'culetSize', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'status', header: 'Status', getterKey: 'status', formatterType: export_interface_1.EFormatterType.REPLACE_WORD, searchValue: '_', newValue: ' ' },
];
exports.profitHeader = [
    { key: 'srNo', header: 'Sr. No' },
    { key: 'orderID', header: 'Order ID', getterKey: 'orderNumber' },
    { key: 'stoneId', header: 'Stone ID', getterKey: 'stoneNo' },
    { key: 'videoLink', header: 'Video', getterKey: '_id', formatterType: export_interface_1.EFormatterType.LINK, webURL: `${config_1.APP_URL}/view-video` },
    { key: 'certificateLink', header: 'Certificate', getterKey: '_id', formatterType: export_interface_1.EFormatterType.LINK, webURL: `${config_1.APP_URL}/view-certificate` },
    { key: 'lab', header: 'Lab', getterKey: 'lab', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'type', header: 'Type', getterKey: 'type', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'inscription', header: 'Inscription', getterKey: 'inscription', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'shape', header: 'Shape', getterKey: 'shape', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'carat', header: 'Carat', style: { numFmt: '0.00' }, getterKey: 'caratWeight', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'color', header: 'Color', getterKey: 'color', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'clarity', header: 'Clarity', getterKey: 'clarity', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'cut', header: 'Cut', getterKey: 'cut', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'polish', header: 'Polish', getterKey: 'polish', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'symmetry', header: 'Symmetry', getterKey: 'symmetry', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'fluorescence', header: 'Fluorescence', getterKey: 'fluorescence', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'orderRap', header: 'Order Rap $', style: { numFmt: '0.00' }, getterKey: 'rap', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'purchaseRap', header: 'Purchase Rap $', style: { numFmt: '0.00' }, getterKey: 'finalRap', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'orderDiscount', header: 'Order Discount %', style: { numFmt: '0.0000' }, getterKey: 'ourDiscount', formatterType: export_interface_1.EFormatterType.DIGIT },
    {
        key: 'purchaseDiscount',
        header: 'Purchase Discount %',
        style: { numFmt: '0.0000' },
        getterKey: 'finalDiscount',
        formatterType: export_interface_1.EFormatterType.DIGIT,
    },
    {
        key: 'orderPricePerCarat',
        header: 'Order Price $ / Carat',
        style: { numFmt: '_($* 0.00_);' },
        getterKey: 'pricePerCarat',
        formatterType: export_interface_1.EFormatterType.DIGIT,
    },
    {
        key: 'purchasePricePerCarat',
        header: 'Purchase Price $ / Carat',
        style: { numFmt: '_($* 0.00_);' },
        getterKey: 'finalPrice',
        formatterType: export_interface_1.EFormatterType.DIGIT,
    },
    {
        key: 'orderAmount',
        header: 'Order  Amount $',
        style: { numFmt: '_($* 0.00_);' },
        getterKey: 'ourPrice',
        formatterType: export_interface_1.EFormatterType.DIGIT,
    },
    {
        key: 'purchaseAmount',
        header: 'Purchase  Amount $',
        style: { numFmt: '_($* 0.00_);' },
        getterKey: 'finalTotalPrice',
        formatterType: export_interface_1.EFormatterType.DIGIT,
    },
    {
        key: 'profit',
        header: 'Profit $',
        style: { numFmt: '_($* 0.00_);_($* -0.00_);' },
        getterKey: 'profit',
        formatterType: export_interface_1.EFormatterType.DIGIT,
    },
    {
        key: 'supplierName',
        header: 'Supplier Name',
        getterKey: 'supplierName',
    },
    {
        key: 'supplierAddress',
        header: 'Supplier Address',
        getterKey: 'supplierAddress',
    },
    {
        key: 'description',
        header: 'Description',
        getterKey: 'description',
    },
    { key: 'location', header: 'Location', getterKey: ['city', 'country'], formatterType: export_interface_1.EFormatterType.FIRST_LETTER_UPPERCASE },
    { key: 'measurement', header: 'Measurement', getterKey: 'measurement' },
    { key: 'depthPercentage', header: 'Depth %', style: { numFmt: '0.00' }, getterKey: 'depthPercentage', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'tablePercentage', header: 'Table %', style: { numFmt: '0.00' }, getterKey: 'tablePercentage', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'heartsAndArrows', header: 'Hearts and Arrows', getterKey: 'heartsAndArrows', formatterType: export_interface_1.EFormatterType.YES_NO },
    { key: 'inclusion', header: 'Inclusion', getterKey: 'inclusion', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'shade', header: 'Shade', getterKey: 'shade', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'milky', header: 'Milky', getterKey: 'milky' },
    { key: 'luster', header: 'Luster', getterKey: 'luster' },
    { key: 'extraFacet', header: 'Extra Facet', getterKey: 'extraFacet' },
    { key: 'internalGraining', header: 'Internal Graining', getterKey: 'internalGraining' },
    { key: 'surfaceGraining', header: 'Surface Graining', getterKey: 'surfaceGraining' },
    {
        key: 'eyeClean',
        header: 'Eye Clean',
        getterKey: 'eyeClean',
        formatterType: export_interface_1.EFormatterType.CUSTOM_FUNCTION,
        getValue: function (value) {
            return (0, helpers_1.getEyeCleanValue)(value).toUpperCase();
        },
    },
    { key: 'ratio', header: 'Ratio', style: { numFmt: '0.00' }, getterKey: 'ratio', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'length', header: 'Length', style: { numFmt: '0.00' }, getterKey: 'length', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'width', header: 'Width', style: { numFmt: '0.00' }, getterKey: 'width', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'height', header: 'Height', style: { numFmt: '0.00' }, getterKey: 'height', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'crownAngle', header: 'Crown Angle', style: { numFmt: '0.00' }, getterKey: 'crownAngle', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'pavilionAngle', header: 'Pavilion Angle', style: { numFmt: '0.00' }, getterKey: 'pavilionAngle', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'crownHeight', header: 'Crown Height', style: { numFmt: '0.00' }, getterKey: 'crownHeight', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'pavilionHeight', header: 'Pavilion Height', style: { numFmt: '0.00' }, getterKey: 'pavilionHeight', formatterType: export_interface_1.EFormatterType.DIGIT },
    { key: 'starLength', header: 'Star Length', getterKey: 'starLength' },
    { key: 'lowerHalves', header: 'Lower Halves', getterKey: 'lowerHalves' },
    { key: 'girdleCondition', header: 'Girdle Condition', getterKey: 'girdleCondition', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE, isMetadata: true },
    {
        key: 'girdlePercentage',
        header: 'Girdle Percentage',
        style: { numFmt: '0.00' },
        getterKey: 'girdlePercentage',
        formatterType: export_interface_1.EFormatterType.DIGIT,
    },
    { key: 'girdleType', header: 'Girdle Type', getterKey: 'girdleType', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'culet', header: 'Culet', getterKey: 'culetSize', formatterType: export_interface_1.EFormatterType.ALL_UPPERCASE },
    { key: 'status', header: 'Status', getterKey: 'status', formatterType: export_interface_1.EFormatterType.REPLACE_WORD, searchValue: '_', newValue: ' ' },
];
//# sourceMappingURL=xlsxUtil.js.map