import { config } from 'dotenv';
config({ path: '.env' });

export const CREDENTIALS = process.env.CREDENTIALS === 'true';
export const { NODE_ENV, PORT, SECRET_KEY, LOG_FORMAT, LOG_DIR, ORIGIN } = process.env;
export const { MONGODB_URI } = process.env;
export const { ADMIN_USERNAME, ADMIN_PASSWORD } = process.env;
export const PAGE_LIMIT = process.env.PAGE_LIMIT ? Number(process.env.PAGE_LIMIT) : 10;
export const {
  SENDER_EMAIL_ID,
  SENDER_EMAIL_PASSWORD,
  MAIL_SERVICE,
  MAIL_HOST,
  MAIL_PORT,
  MAIL_SECURE,
  SENDER_NAME,
  COMPANY_ADDRESS,
  INFO_EMAIL,
  COMPANY_LOGO,
  SUPPORT_EMAIL,
} = process.env;
export const {
  UPLOAD_DIAMOND_CRON_INTERVAL,
  UPLOAD_DIAMOND_LIMIT,
  FILE_STONE_NUMBER_PREFIX,
  MAITRI_STONE_NUMBER_PREFIX,
  MAITRI_AUTH_TOKEN,
  MAITRI_API_URL,
  ANJALI_STONE_NUMBER_PREFIX,
  ANJALI_SOURCE_API_URL,
  ANJALI_SOURCE_AUTH_TOKEN,
  ECOSTAR_STONE_NUMBER_PREFIX,
  ECOSTAR_SOURCE_API_URL,
  ECOSTAR_SOURCE_AUTH_TOKEN,
  BAPA_SITARAM_SOURCE_API_URL,
  BAPA_SITARAM_API_KEY,
  BAPA_SITARAM_STONE_NUMBER_PREFIX,
  RAPNET_API_CLIENT_ID,
  RAPNET_API_CLIENT_SECRET,
  RAPNET_API_GET_TOKEN_URL,
  RAPNET_API_GET_PRICE_LIST,
} = process.env;
export const APP_URL = process.env.APP_URL;
export const INITIAL_ORDER_NUMBER = process.env.INITIAL_ORDER_NUMBER ? Number(process.env.INITIAL_ORDER_NUMBER) - 1 : 0;
export const ORDER_NUMBER_PREFIX = process.env.ORDER_NUMBER_PREFIX;
