export const uploadDiamondsFileHeader = {
  stoneNo: 'Stone No',
  lab: 'Lab',
  shape: 'Shape',
  carat: 'Carat',
  color: 'Color',
  clarity: 'Clarity',
  cut: 'Cut',
  polish: 'Polish',
  symmetry: 'Symmetry',
  diamondType: 'Diamond Type',
  type: 'Sub Type',
  shade: 'Shade',
  rap: 'Rap $',
  pricePerCarat: 'Price/Carat $',
  discount: 'Discount %',
  price: 'Price $',
  inscription: 'Inscription',
  noBGM: 'No BGM',
  country: 'Country',
  city: 'City',
  luster: 'Luster',
  milky: 'Milky',
  eyeClean: 'Eye Clean %',
  measurement: 'Measurement',
  width: 'Width',
  height: 'Height',
  florescence: 'Florescence',
  inclusion: 'Inclusion',
  extraFacet: 'Extra Facet',
  internalGraining: 'Internal Graining',
  surfaceGraining: 'Surface Graining',
  heartsAndArrows: 'Hearts And Arrows',
  culetSize: 'Culet Size',
  fancyColor: 'Fancy Color',
  fancyIntensity: 'Fancy Intensity',
  fancyOvertone: 'Fancy Overtone',
  length: 'Length',
  depthPercentage: 'Depth %',
  tablePercentage: 'Table %',
  crownAngle: 'Crown Angle',
  crownHeight: 'Crown Height',
  pavilionAngle: 'Pavilion Angle',
  pavilionHeight: 'Pavilion Height',
  starLength: 'Star Length',
  lowerHalves: 'Lower Halves',
  girdleType: 'Girdle Type',
  girdlePercentage: 'Girdle %',
  girdleCondition: 'Girdle Condition',
  ratio: 'Ratio',
  videoLink: 'Video Link',
  imageLink: 'Image Link',
  certificateLink: 'Certificate Link',
  keyToSymbol: 'Key To Symbol',
  notes: 'Notes',
  motibaGemsComment: 'Motiba Gems Comment',
  certificateComment: 'Certificate Comment',
  status: 'Status',
};

export const diamondTypeValues = ['lab grown', 'natural'];
export const labGrownTypeValues = ['cvd', 'hpht'];
export const inscriptionValues = ['yes', 'no'];
export const noBGMValues = ['yes', 'no'];
export const heartsAndArrowsValues = ['yes', 'no'];
export const statusValues = ['available', 'sold'];
export const labGrownLabValues = ['igi', 'gia', 'hrd', 'none'];
export const naturalLabValues = ['gia', 'igi', 'hrd', 'fm', 'ngtc', 'iidgr', 'none'];
export const shapeValues = ['round', 'cushion', 'marquise', 'pear', 'princess', 'heart', 'oval', 'emerald', 'radiant', 'square emerald'];
export const colorValues = ['d', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q-r', 's-t', 'u-v', 'w-x', 'y-z'];
export const clarityValues = ['fl', 'if', 'vvs1', 'vvs2', 'vs1', 'vs2', 'si1', 'si2', 'si3', 'i1', 'i2', 'i3'];
export const cutValues = ['id', 'ex', 'vg', 'gd', 'fr'];
export const polishValues = ['id', 'ex', 'vg', 'gd', 'fr'];
export const symmetryValues = ['id', 'ex', 'vg', 'gd', 'fr'];
export const lusterValues = ['id', 'ex', 'vg', 'gd', 'fr'];
export const eyeCleanRange = { from: 0, to: 100 };
export const labGrownCuletSizeValues = ['none', 'pointed', 'long'];
export const naturalCuletSizeValues = ['non', 'vs', 's', 'm', 'l', 'vl'];
export const fancyColorValues = [
  'fancy light yellow',
  'gray blue',
  'green blue',
  'light grey blue',
  'vivid green blue',
  'yellow',
  'pink',
  'blue',
  'red',
  'green',
  'purple',
  'orange',
  'violet',
  'gray',
  'black',
  'brown',
  'champagne',
  'cognac',
  'chameleon',
  'white',
  'other',
  'brown yellow',
  'orange yellow',
  'green yellow',
  'orangy yellow',
  'brown pink',
  'purple pink',
  'bluish green',
  'yellow green',
  'pink purple',
  'yellow orange',
  'brown orange',
  'yellow grey',
  'yellow brown',
  'pink brown',
  'orange brown',
  'green chameleon',
];
export const fancyIntensityValues = [
  'faint',
  'very light',
  'light',
  'fancy light',
  'fancy',
  'fancy dark',
  'fancy intense',
  'fancy vivid',
  'fancy deep',
  'fancy natural',
];
export const fancyOvertoneValues = [
  'brown',
  'gray',
  'pink',
  'yellow',
  'none',
  'yellowish',
  'pinkish',
  'bluish',
  'reddish',
  'greenish',
  'purplish',
  'orangey',
  'grayish',
  'brownish',
  'brown orangey',
  'brownish greenish',
  'brownish yellowish',
  'grayish greenish',
  'grayish yellowish',
];
export const keyToSymbolValues = [
  'bearding',
  'chip',
  'crystal surface',
  'flux remnant',
  'internal laser drilling',
  'minor details of polish',
  'pinpoint',
  'brown patch of color',
  'cleavage',
  'etch channel',
  'indented natural',
  'knot',
  'natural',
  'reflecting surface graining',
  'bruise',
  'cloud',
  'extra facet',
  'internal graining',
  'laser drill hole',
  'needle',
  'surface graining',
  'cavity',
  'crystal',
  'feather',
  'internal inscription',
  'manufacturing remnant',
  'no inclusion',
  'twining wisp',
];

export const uploadViaFileValues = [
  ['NOTE: NOT CASE SENSITIVE', ''],
  ['Diamond Types ', diamondTypeValues.join(', ')],
  ['Lab Grown Types ', labGrownTypeValues.join(', ')],
  ['Inscription ', inscriptionValues.join('/')],
  ['No BGM ', noBGMValues.join('/')],
  ['Hearts and Arrows ', heartsAndArrowsValues.join('/')],
  ['Status ', statusValues.join('/')],
  ['Lab [Lab Grown] ', labGrownLabValues.join(', ')],
  ['Lab [Natural] ', naturalLabValues.join(', ')],
  ['Shape ', shapeValues.join(', ')],
  ['Color ', colorValues.join(', ')],
  ['Clarity ', clarityValues.join(', ')],
  ['Cut ', cutValues.join(', ')],
  ['Polish ', polishValues.join(', ')],
  ['Symmetry ', symmetryValues.join(', ')],
  ['Luster ', lusterValues.join(', ')],
  ['Eye Clean ', `${eyeCleanRange.from} - ${eyeCleanRange.to}`],
  ['Culet Size [Lab grown] ', labGrownCuletSizeValues.join(', ')],
  ['Culet Size [Natural] ', naturalCuletSizeValues.join(', ')],
  ['Fancy Color ', fancyColorValues.join(', ')],
  ['Fancy Intensity ', fancyIntensityValues.join(', ')],
  ['Fancy Overtone ', fancyOvertoneValues.join(', ')],
  ['Key To Symbol ', keyToSymbolValues.join(', ')],
];

export const excelExtensions = ['xlsx', 'csv', 'xls'];
